### VARIABLES GLOBALES
@api = http://localhost:3000/api/v1/products
@categoryApi = http://localhost:3000/api/v1/categories

# ==========================================
# 0. SETUP: NECESITAMOS CATEGORÍAS
# ==========================================

### Crear Categoría Bebida
# @name createCategoryDrink
POST {{categoryApi}}
Content-Type: application/json

{
    "name": "Bebidas",
    "description": "Refrescos y jugos"
}

@drinkCategoryId = {{createCategoryDrink.response.body.newCategory._id}}

# ==========================================
# 1. PRODUCTOS (CORE)
# ==========================================

### Crear Producto 1 (Coca Cola)
# @name createProd1
POST {{api}}
Content-Type: application/json

{
    "name": "Coca Cola Zero",
    "description": "Refresco sin azucar",
    "category": "{{drinkCategoryId}}",
    "type": "dish",
    "price": 2.50,
    "portion_size": "355ml"
}

### Crear Producto 2 (Pepsi)
# @name createProd2
POST {{api}}
Content-Type: application/json

{
    "name": "Pepsi Regular",
    "description": "Refresco de cola",
    "category": "{{drinkCategoryId}}",
    "type": "dish",
    "price": 2.20,
    "portion_size": "355ml"
}

@dishId = {{createProd1.response.body.newProduct._id}}

# ==========================================
# 2. CONSULTAS AVANZADAS (SEARCH & PAGINATION)
# ==========================================

### 2.1 Obtener Todos (Paginación por defecto)
# Deberia retornar page:1, limit:10 (o lo definido en backend)
GET {{api}}

### 2.2 Paginación Personalizada
# Pagina 1, solo 1 elemento
GET {{api}}?page=1&limit=1

### 2.3 Paginación: Segunda Página
# Deberia traer el siguiente producto si creaste al menos 2
GET {{api}}?page=2&limit=1

### 2.4 Búsqueda por Texto
# Busca productos que contengan "Coca"
GET {{api}}?search=Coca

### 2.5 Filtrar por Tipo
GET {{api}}?type=dish

### 2.6 Filtrar por Categoría
GET {{api}}?category={{drinkCategoryId}}

### 2.7 Filtrar por Estado (Active/Inactive)
GET {{api}}?status=active

### 2.8 COMBINACIÓN COMPLETA
# Buscar "Coca" que sea "dish", esté "active", pagina 1, limite 5
GET {{api}}?search=Coca&type=dish&status=active&page=1&limit=5

# ==========================================
# 3. OPERACIONES CRUD (ID)
# ==========================================

### Obtener por ID
GET {{api}}/{{dishId}}

### Actualizar Precio
PUT {{api}}/{{dishId}}
Content-Type: application/json

{
    "price": 3.00
}

### Borrar (Soft Delete)
DELETE {{api}}/{{dishId}}


# ==========================================
# 4. SUB-RECURSOS (NUTRICIÓN E INGREDIENTES)
# ==========================================

### Agregar Información Nutricional
PUT {{api}}/{{dishId}}/nutrition
Content-Type: application/json

{
    "calories": 0,
    "sugar": 0,
    "sodium": 40
}

### Ver Info Nutricional
GET {{api}}/{{dishId}}/nutrition
